import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "@/assets/styles/_index.scss";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased appContainer`}
      >
        <header>
          <div className="containerContent flex justify-between">
            <Link href="/" className="navbar-brand" aria-label="Site branding">
              <span className="brand-name" aria-label="Candidate's name">
                Ivan Ontiveros
              </span>
              <span className="title">
                Software Engineer at Aetna, a CVS Health Company
              </span>
              <span className="location">Buckeye, Arizona, United States</span>
            </Link>
            <nav className="text-right grid items-end">
              <ul className="flex space-x-4">
                <li className="text-lg">
                  <Link href="/">Home</Link>
                </li>
                <li className="text-lg">
                  <Link href="/about">About</Link>
                </li>
                <li className="text-lg">
                  <Link href="/skills">Skills & Certifications</Link>
                </li>
                <li className="text-lg">
                  <Link href="/resume">Resume</Link>
                </li>
                <li className="text-lg">
                  <Link href="/contact">Contact</Link>
                </li>
              </ul>
            </nav>
          </div>
        </header>
        <main>
          <div className="containerContent">{children}</div>
        </main>
        <footer>
          <div className="containerContent">
            &copy; 2024-2025 Ivan Ontiveros. All rights reserved.
          </div>
        </footer>
      </body>
    </html>
  );
}
